// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayznevgdmkbprwxftsuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5em5ldmdkbWticHJ3eGZ0c3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDc3NDcsImV4cCI6MjA2MzU4Mzc0N30.s9K2bLTCz_8PwfeciS1ZcmQgCfCg6jdByrdyvRwH3HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);